- name: openconfig-extensions
  docs:
    - yang/extensions/openconfig-codegen-extensions.yang
  build:
    - yang/extensions/openconfig-codegen-extensions.yang
  run-ci: true
- name: openconfig-metadata
  docs:
    - yang/extensions/openconfig-metadata.yang
  build:
    - yang/extensions/openconfig-metdata.yang
  run-ci: true
